name: Show Files on Push

on:
  push:
    branches:
      - mes-dates

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -R

      - name: Run PHPCS
        run: |
          composer require --dev squizlabs/php_codesniffer
          vendor/bin/phpcs --standard=PSR12 src/

        
