name: CI - Lint et Vérification

on: [push, pull_request]

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  
          tools: phpcs, composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: List files
        run: ls -la

      - name: Run PHPCS
        run: phpcs --standard=PSR12 src/
