name: PHP Code Sniffer

on:
  push:
    branches:
      - mes-dates
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.1.1'
          tools: phpcs

      - name: Run PHPCS
        run: |
          phpcs --standard=PSR12 --ignore=vendor . || exit 1
